#!/usr/bin/perl

use qPXE::Lab;
use qPXE::Test::BasicDhcpHttp;
use strict;
use warnings;

my $lab = qPXE::Lab->new ( uri => "qemu:///system" );
my $test = qPXE::Test::BasicDhcpHttp->new ( lab => $lab );

$test->prepare();
$test->execute();
$test->cleanup();
